
seed_everything: true
trainer:
  # trainer options
  enable_checkpointing: true
  fast_dev_run: false
  max_epochs: 100
  limit_train_batches: 10000
  limit_val_batches: 500
  log_every_n_steps: 50
  accelerator: gpu
  precision: 16
  num_sanity_val_steps: 10
  benchmark: false
  deterministic: true
  auto_lr_find: false

  # callbacks
  callbacks:
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        monitor: val_loss
        mode: min
        save_top_k: 1
        save_last: true
        filename: '{epoch}-{val_loss:.2f}'
        dirpath: checkpoints
        verbose: true

    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        monitor: val_loss
        mode: min
        patience: 10
        verbose: true

    - class_path: pytorch_lightning.callbacks.TQDMProgressBar
      init_args:
        refresh_rate: 100
    

data:
  train_file: debug_file.parquet
  val_file: debug_file.parquet
  data_path: /eos/user/r/rradev/top_data/TopLandscape/
  data_config_file: top_landscape.yaml
  batch_size: 128
  num_workers: 1
  fetch_step: 1.0
  in_memory: true

ckpt_path: null
